In [1]:
import pandas as pd
import numpy as np
import csv

In [11]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
a.shape

(4, 3)

In [9]:
a1 = a[0:2]
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a2 = a[2:4]
a2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [12]:
A = (a1,a2)
A

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [32]:
X = np.vstack(A)
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
X.shape

(4, 3)

In [16]:
a.shape[0]

4

In [20]:
n = a.shape[0] / 2
int(n)

2

In [21]:
n=int(n)

In [39]:
x=[]
start = 0
end = n
for i in range(n):
    x.append(a[start: end])
    start = start+n
    end = end+n

In [40]:
x

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [41]:
X = np.vstack(x)

In [42]:
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [2]:
file_path = './dataset/train.csv'
escape_char_defined = "\\"
train_data = pd.read_csv(file_path, error_bad_lines=False, quoting=csv.QUOTE_NONE, escapechar=escape_char_defined)
train_data.head()

/home/abhishek/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


TITLE  \
0         Pete The Cat Bedtime Blues Doll, 14.5 Inch   
1  The New Yorker NYHM014 Refrigerator Magnet, 2 ...   
2  The Ultimate Self-Sufficiency Handbook: A Comp...   
3   Amway Nutrilite Kids Chewable Iron Tablets (100)   
4  Teacher Planner Company A4 6 Lesson Academic T...   

                                         DESCRIPTION  \
0  Pete the Cat is the coolest, most popular cat ...   
1  The New Yorker Handsome Cello Wrapped Hard Mag...   
2                                                NaN   
3                                                NaN   
4                                                NaN   

                                       BULLET_POINTS           BRAND  \
0  [Pete the Cat Bedtime Blues plush doll,Based o...     MerryMakers   
1  [Cat In A Tea Cup by New Yorker cover artist G...  The New Yorker   
2                                Skyhorse Publishing          imusti   
3  [Nutrilite Kids,Chewable Iron Tablets,Quantity...           Amway   
4                                                NaN             NaN   

   BROWSE_NODE_ID  
0               0  
1               1  
2               2  
3               3  
4               4

In [3]:
train_data = train_data.dropna(axis=0)

In [4]:
df = train_data.sample(n=800000)

In [5]:
df.shape

(800000, 5)

In [6]:
df.head()

TITLE  \
1829007  in-Ear Headphones R 20 Earphones for Xiaomi Re...   
1900577  Style Store Men's Velvet Closed Executive Form...   
1223071  Shopsmeade I Will Be No.1 - Katsuki Bakugo Mug...   
1623189  MJDCNC V8 Bluetooth Smartwatch Compatible with...   
2111578   Keshav Temples Dakshinavarti Shankh - with Curls   

                                               DESCRIPTION  \
1829007  Double moving coil loud speakers deliver wonde...   
1900577  Rendered with the modern-day appeal, this marv...   
1223071  Shopsmeade mugs are a great gift for any occas...   
1623189  ABOUT THE PRODUCT External Dimension: 53.0X44....   
2111578  Right Handed Shankh Non-Blowable Natural Curls...   

                                             BULLET_POINTS         BRAND  \
1829007  [Enjoy the powerful 11.2mm bass boost driver w...  ShopsGeniune   
1900577  [Sole: Airmix,It is nice affordable shoes for ...   Style Store   
1223071  [Unique designs, 100% Premium printing, Author...    Shopsmeade   
1623189  [SMARTWATCH FEATURE:- 1.54 HD TFT High Sensiti...        MJDCNC   
2111578  Right Handed Shankh Non-Blowable Natural Curls...    KESHAV JEE   

         BROWSE_NODE_ID  
1829007             811  
1900577            1409  
1223071              11  
1623189             507  
2111578            1287

In [7]:
df.to_csv("train_800k.csv")

In [8]:
file_path = 'train_800k.csv'
train_data = pd.read_csv(file_path, index_col=0)
train_data

TITLE  \
1829007  in-Ear Headphones R 20 Earphones for Xiaomi Re...   
1900577  Style Store Men's Velvet Closed Executive Form...   
1223071  Shopsmeade I Will Be No.1 - Katsuki Bakugo Mug...   
1623189  MJDCNC V8 Bluetooth Smartwatch Compatible with...   
2111578   Keshav Temples Dakshinavarti Shankh - with Curls   
...                                                    ...   
2485380            Derbenny Camouflage Windcheater for Men   
1591010  Itspleazure Detachable and Adjustable Butterfl...   
2482114  Shengshou Mobile Back Cover for Samsung Galaxy...   
1632162  Ejoyous Infrared Beam Waterproof Security Aler...   
23642    kinbor Patio Wicker Furniture Sectional Sofa S...   

                                               DESCRIPTION  \
1829007  Double moving coil loud speakers deliver wonde...   
1900577  Rendered with the modern-day appeal, this marv...   
1223071  Shopsmeade mugs are a great gift for any occas...   
1623189  ABOUT THE PRODUCT External Dimension: 53.0X44....   
2111578  Right Handed Shankh Non-Blowable Natural Curls...   
...                                                    ...   
2485380  An All - Time Classic Style For Every Metro Ma...   
1591010  Detachable & Adjustable Butterfly Swing Set & ...   
2482114  Shengshou back covers are the best attractive ...   
1632162  <b>Description:</b><br> This is a pair of infr...   
23642    <p><b>Description:</b></p> <p>Make your patio ...   

                                             BULLET_POINTS         BRAND  \
1829007  [Enjoy the powerful 11.2mm bass boost driver w...  ShopsGeniune   
1900577  [Sole: Airmix,It is nice affordable shoes for ...   Style Store   
1223071  [Unique designs, 100% Premium printing, Author...    Shopsmeade   
1623189  [SMARTWATCH FEATURE:- 1.54 HD TFT High Sensiti...        MJDCNC   
2111578  Right Handed Shankh Non-Blowable Natural Curls...    KESHAV JEE   
...                                                    ...           ...   
2485380  [Full zip closure on the front,Attached hood w...      Derbenny   
1591010  [Detachable & Adjustable Butterfly Swing Set &...   Itspleazure   
2482114  [Sublimation Cover,Hard Cover,Designed and Pri...     Shengshou   
1632162  [▲ Infrared beam sensor, Its four channel freq...       Ejoyous   
23642    [Please measure the size information of your o...        kinbor   

         BROWSE_NODE_ID  
1829007             811  
1900577            1409  
1223071              11  
1623189             507  
2111578            1287  
...                 ...  
2485380           30478  
1591010            9285  
2482114            1045  
1632162              43  
23642               912  

[800000 rows x 5 columns]

In [9]:
train_data.shape

(800000, 5)

In [15]:
import multiprocessing

def worker():
    """worker function"""
    print("a")
    return




In [24]:
jobs = []
for i in range(5):
    p = multiprocessing.Process(target=worker)
    jobs.append(p)
    p.start()

a
a
a

aa


In [28]:
def a():
    print("a")
def b():
    print("b")
def c():
    print("c")
def d():
    print("d")
def e():
    print("e")
def f():
    print("f")
def g():
    print("g")
def h():
    print("h")
def i():
    print("i")
def j():
    print("j")
    

In [30]:
p = multiprocessing.Process(target=a)
p.start()
p = multiprocessing.Process(target=b)
p.start()
p = multiprocessing.Process(target=c)
p.start()
p = multiprocessing.Process(target=d)
p.start()
p = multiprocessing.Process(target=e)
p.start()
p = multiprocessing.Process(target=f)
p.start()
p = multiprocessing.Process(target=g)
p.start()
p = multiprocessing.Process(target=h)
p.start()
p = multiprocessing.Process(target=i)
p.start()
p = multiprocessing.Process(target=j)
p.start()

a

bc
d
e
f
g
h
i
j


In [48]:
# Python program to illustrate the concept
# of threading
# importing the threading module
import threading
cu=0
sq=0
def print_cube(num, a):
	"""
	function to print cube of given num
	"""
	a = num*num*num
	print(a)
	print("Cube: {}".format(num * num * num))

def print_square(num):
	"""
	function to print square of given num
	"""
	sq=num*num
	print("Square: {}".format(num * num))

if __name__ == "__main__":
	# creating thread
	t1 = threading.Thread(target=print_square, args=(10,cu))
	t2 = threading.Thread(target=print_cube, args=(10,))

	# starting thread 1
	t1.start()
	# starting thread 2
	t2.start()

	# wait until thread 1 is completely executed
	t1.join()
	# wait until thread 2 is completely executed
	t2.join()

	# both threads completely executed
	print("Done!")


Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)    
TypeError: print_square() takes 1 positional argument but 2 were given
self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
TypeError: print_cube() missing 1 required positional argument: 'a'


Done!


In [46]:
cu


0

In [47]:
sq

0